name: Generate and store artifacts

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Cache assets
        id: cache-assets
        uses: actions/cache@v4
        with:
          path: artifacts
          key: ${{ github.run_number }}-assets

      - name: Generate artifacts
        run: |
          mkdir -p artifacts
          for i in {1..10}; do
            curl "https://baconipsum.com/api/?type=meat-and-filler&paras=3&format=text" > artifacts/artifact_$i.txt
          done

      # - name: Store generated artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: ${{ github.run_number }}-assets
      #     path: artifacts/*
      #     compression-level: 0
  
  list:
    runs-on: ubuntu-latest
    needs: generate
    steps:
      - name: Attach cache
        id: cache-assets
        uses: actions/cache@v4
        with:
          path: artifacts
          key: ${{ github.run_number }}-assets

      # - name: Download artifacts
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: ${{ github.run_number }}-assets
      
      - name: echo path
        run: tree -a
