name: Dynamic build image on file change

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      folders: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            folder1: dynamic_repo/folder1
            folder2: dynamic_repo/folder2

  build:
    runs-on: ubuntu-latest
    needs: changes
    strategy:
      matrix:
        folder: ${{ fromJSON(needs.changes.outputs.folders) }}
    steps:
      - uses: actions/checkout@v4
      - name: Echo folder
        run: |
          echo 'Folder with changes: ${{ matrix.folder }}'
