name: Get branch name

on:
  push:
    branches:
      - develop
      - main

jobs:
  get-branch:
    runs-on: ubuntu-latest
  
    env:
      BRANCH_NAME: ${{ github.ref_name }}
    
    steps:
      - name: print-branch
        run: echo $BRANCH_NAME
